### ISSUE TITLE
Create the end point for get all Leads

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm-node-api#18]
Create the Leads end point to get all the data 
- The end point should be `GET /leads`
- Should check for the module permission and the view action permitted or not
- The field should be added for attributes are

``` sql
+---------------+------------------+
| field_name    | table_name       |
+---------------+------------------+
| firstname     | leads            |
| lastname      | leads            |
| email         | leads            |
| phone         | leads            |
| mobile        | leads            |
| title         | leads            |
| fax           | leads            |
| leadsource    | leads            |
| industry      | leads            |
| organization  | leads            |
| website       | leads            |
| lead_status   | leads            |
| anual_revenue | leads            |
| rating        | leads            |
| description   | leads            |
| assigned_to   | leads            |
| street        | leads_address    |
| po_box        | leads_address    |
| postal_code   | leads_address    |
| country       | leads_address    |
| city          | leads_address    |
| state         | leads_address    |
| added_on      | leads            |
| last_modified | leads            |
| converted     | leads            |
| idleads       | leads            |

```
- We will not add custom fields for now.
- Should follow the JSONAPI standard
- Attributes should be camel case.
- Should support pagination

**Comment by abhikchakraborty** [comment]
The end point is ready and here is the PR https://github.com/sQcrm/sqcrm-node-api/pull/19

Here are few things to be noted
- We had to use the `query` method of the ORM since the query is pretty complicated and currently some of the things are not supported within the built-in functions.
- Since `query` function is used to execute row query, it can not use the model attributes directly and hence anything added in the model using camel case does not make any difference.
- For the above step we have used the JSONAPI serializer's functionality to camelize the response.
- Currently the response is pretty simple and its more like `populate` function of the ORM for the related data
- Not added the included element and we shall not do that, since we will have different endpoint for related informations later.
